// Generated from unified.db's `channel` table (pretty/attribute
// columns, majority-voted per normalized name, weighted toward
// GDTF-sourced evidence - see
// ~/.claude/projects/.../unified-fixture-db.md). Run
// scripts/update_channel_attribute_map.py to refresh this file. Do
// not hand-edit.
// Entry count: 489
part of 'channel_attribute_map.dart';

const channelAttributeMap = <String, String>{
  '1 amber': 'ColorAdd_RY',
  '1 blue': 'ColorAdd_B',
  '1 dimmer': 'Dimmer',
  '1 green': 'ColorAdd_G',
  '1 red': 'ColorAdd_R',
  '1 tilt': 'Tilt',
  '1 warm white': 'ColorAdd_WW',
  '1 white': 'ColorAdd_W',
  '10 blue': 'ColorAdd_B',
  '10 green': 'ColorAdd_G',
  '10 red': 'ColorAdd_R',
  '10 white': 'ColorAdd_W',
  '11 blue': 'ColorAdd_B',
  '11 green': 'ColorAdd_G',
  '11 red': 'ColorAdd_R',
  '11 white': 'ColorAdd_W',
  '12 blue': 'ColorAdd_B',
  '12 green': 'ColorAdd_G',
  '12 red': 'ColorAdd_R',
  '12 white': 'ColorAdd_W',
  '13 blue': 'ColorAdd_B',
  '13 green': 'ColorAdd_G',
  '13 red': 'ColorAdd_R',
  '13 white': 'ColorAdd_W',
  '14 blue': 'ColorAdd_B',
  '14 green': 'ColorAdd_G',
  '14 red': 'ColorAdd_R',
  '14 white': 'ColorAdd_W',
  '15 blue': 'ColorAdd_B',
  '15 green': 'ColorAdd_G',
  '15 red': 'ColorAdd_R',
  '15 white': 'ColorAdd_W',
  '16 blue': 'ColorAdd_B',
  '16 green': 'ColorAdd_G',
  '16 red': 'ColorAdd_R',
  '16 white': 'ColorAdd_W',
  '17 blue': 'ColorAdd_B',
  '17 green': 'ColorAdd_G',
  '17 red': 'ColorAdd_R',
  '17 white': 'ColorAdd_W',
  '18 blue': 'ColorAdd_B',
  '18 green': 'ColorAdd_G',
  '18 red': 'ColorAdd_R',
  '18 white': 'ColorAdd_W',
  '19 blue': 'ColorAdd_B',
  '19 green': 'ColorAdd_G',
  '19 red': 'ColorAdd_R',
  '19 white': 'ColorAdd_W',
  '2 amber': 'ColorAdd_RY',
  '2 blue': 'ColorAdd_B',
  '2 dimmer': 'Dimmer',
  '2 green': 'ColorAdd_G',
  '2 red': 'ColorAdd_R',
  '2 tilt': 'Tilt',
  '2 warm white': 'ColorAdd_WW',
  '2 white': 'ColorAdd_W',
  '20 blue': 'ColorAdd_B',
  '20 green': 'ColorAdd_G',
  '20 red': 'ColorAdd_R',
  '21 blue': 'ColorAdd_B',
  '21 green': 'ColorAdd_G',
  '21 red': 'ColorAdd_R',
  '22 blue': 'ColorAdd_B',
  '22 green': 'ColorAdd_G',
  '22 red': 'ColorAdd_R',
  '23 blue': 'ColorAdd_B',
  '23 green': 'ColorAdd_G',
  '23 red': 'ColorAdd_R',
  '24 blue': 'ColorAdd_B',
  '24 green': 'ColorAdd_G',
  '24 red': 'ColorAdd_R',
  '25 blue': 'ColorAdd_B',
  '25 green': 'ColorAdd_G',
  '25 red': 'ColorAdd_R',
  '26 blue': 'ColorAdd_B',
  '26 green': 'ColorAdd_G',
  '26 red': 'ColorAdd_R',
  '27 blue': 'ColorAdd_B',
  '27 green': 'ColorAdd_G',
  '27 red': 'ColorAdd_R',
  '28 blue': 'ColorAdd_B',
  '28 green': 'ColorAdd_G',
  '28 red': 'ColorAdd_R',
  '29 blue': 'ColorAdd_B',
  '29 green': 'ColorAdd_G',
  '29 red': 'ColorAdd_R',
  '3 amber': 'ColorAdd_RY',
  '3 blue': 'ColorAdd_B',
  '3 dimmer': 'Dimmer',
  '3 green': 'ColorAdd_G',
  '3 red': 'ColorAdd_R',
  '3 tilt': 'Tilt',
  '3 white': 'ColorAdd_W',
  '30 blue': 'ColorAdd_B',
  '30 green': 'ColorAdd_G',
  '30 red': 'ColorAdd_R',
  '31 blue': 'ColorAdd_B',
  '31 green': 'ColorAdd_G',
  '31 red': 'ColorAdd_R',
  '32 blue': 'ColorAdd_B',
  '32 green': 'ColorAdd_G',
  '32 red': 'ColorAdd_R',
  '4 amber': 'ColorAdd_RY',
  '4 blue': 'ColorAdd_B',
  '4 dimmer': 'Dimmer',
  '4 green': 'ColorAdd_G',
  '4 red': 'ColorAdd_R',
  '4 tilt': 'Tilt',
  '4 white': 'ColorAdd_W',
  '5 amber': 'ColorAdd_RY',
  '5 blue': 'ColorAdd_B',
  '5 dimmer': 'Dimmer',
  '5 green': 'ColorAdd_G',
  '5 red': 'ColorAdd_R',
  '5 tilt': 'Tilt',
  '5 white': 'ColorAdd_W',
  '6 amber': 'ColorAdd_RY',
  '6 blue': 'ColorAdd_B',
  '6 dimmer': 'Dimmer',
  '6 green': 'ColorAdd_G',
  '6 red': 'ColorAdd_R',
  '6 tilt': 'Tilt',
  '6 white': 'ColorAdd_W',
  '7 blue': 'ColorAdd_B',
  '7 dimmer': 'Dimmer',
  '7 green': 'ColorAdd_G',
  '7 red': 'ColorAdd_R',
  '7 white': 'ColorAdd_W',
  '8 blue': 'ColorAdd_B',
  '8 green': 'ColorAdd_G',
  '8 red': 'ColorAdd_R',
  '8 white': 'ColorAdd_W',
  '9 blue': 'ColorAdd_B',
  '9 green': 'ColorAdd_G',
  '9 red': 'ColorAdd_R',
  '9 white': 'ColorAdd_W',
  'amber': 'ColorAdd_RY',
  'animation': 'AnimationWheel{n}',
  'animation wheel': 'AnimationWheel{n}',
  'animationsystem': 'AnimationSystem{n}',
  'animationsystem 1 macro': 'AnimationSystem{n}Macro',
  'animationsystem 1 pos': 'AnimationSystem{n}Pos',
  'animationwheel': 'AnimationWheel{n}',
  'animationwheel 1 macro': 'AnimationWheel{n}Macro',
  'animationwheel 1 pos': 'AnimationWheel{n}Pos',
  'animationwheel 1 posrotate': 'AnimationWheel{n}PosRotate',
  'animationwheel 1 selecteffects': 'AnimationWheel{n}SelectEffects',
  'aura blue': 'ColorAdd_B',
  'aura green': 'ColorAdd_G',
  'aura red': 'ColorAdd_R',
  'auto focus': 'Focus{n}',
  'auto mode': 'Effects{n}',
  'auto prog': 'Effects{n}',
  'auto program': 'Effects{n}',
  'auto programs': 'Effects{n}',
  'auto sound': 'Effects{n}',
  'background blue': 'ColorAdd_B',
  'background color': 'Color{n}',
  'background dimmer': 'Dimmer',
  'background green': 'ColorAdd_G',
  'background red': 'ColorAdd_R',
  'background white': 'ColorAdd_W',
  'beam dimmer': 'Dimmer',
  'beamreset': 'BeamReset',
  'beamshaper': 'BeamShaper',
  'beamshapermacro': 'BeamShaperMacro',
  'beamshaperpos': 'BeamShaperPos',
  'beamshaperposrotate': 'BeamShaperPosRotate',
  'bg blue': 'ColorAdd_B',
  'bg col': 'Color{n}',
  'bg dimmer': 'Dimmer',
  'bg green': 'ColorAdd_G',
  'bg red': 'ColorAdd_R',
  'bg strobe': 'Shutter{n}Strobe',
  'bg white': 'ColorAdd_W',
  'blackoutmode': 'BlackoutMode',
  'blade': 'Blade{n}A',
  'blade 1 a': 'Blade{n}A',
  'blade 1 b': 'Blade{n}B',
  'blade 1 rot': 'Blade{n}Rot',
  'blade 2 a': 'Blade{n}A',
  'blade 2 b': 'Blade{n}B',
  'blade 2 rot': 'Blade{n}Rot',
  'blade 3 a': 'Blade{n}A',
  'blade 3 b': 'Blade{n}B',
  'blade 3 rot': 'Blade{n}Rot',
  'blade 4 a': 'Blade{n}A',
  'blade 4 b': 'Blade{n}B',
  'blade 4 rot': 'Blade{n}Rot',
  'blade rot': 'Blade{n}A',
  'blue': 'ColorAdd_B',
  'bot w': 'Dimmer',
  'chase': 'Effects{n}',
  'chase fade': 'Effects{n}',
  'cie brightness': 'CIE_Brightness',
  'cie x': 'CIE_X',
  'cie y': 'CIE_Y',
  'cmy macro': 'ColorMacro{n}',
  'col fx': 'Effects{n}',
  'col macro': 'ColorMacro{n}',
  'col macros': 'ColorMacro{n}',
  'col mix': 'Color{n}',
  'col mode': 'Function',
  'col preset': 'FixtureGlobalReset',
  'col presets': 'FixtureGlobalReset',
  'col select': 'Color{n}',
  'col speed': 'GlobalMSpeed',
  'col temp': 'Color{n}',
  'cold white': 'ColorAdd_CW',
  'color': 'Color{n}',
  'color 1 mode': 'Color{n}Mode',
  'color 1 wheelindex': 'Color{n}WheelIndex',
  'color 1 wheelspin': 'Color{n}WheelSpin',
  'color chase': 'Color{n}',
  'color function': 'Color{n}',
  'color macro': 'ColorMacro{n}',
  'color macros': 'ColorMacro{n}',
  'color presets': 'ColorMacro{n}',
  'color selection': 'Color{n}',
  'color temp': 'CTO',
  'color temperature': 'CTO',
  'color wheel': 'Color{n}',
  'coloradd b': 'ColorAdd_B',
  'coloradd bc': 'ColorAdd_BC',
  'coloradd bm': 'ColorAdd_BM',
  'coloradd c': 'ColorAdd_C',
  'coloradd cw': 'ColorAdd_CW',
  'coloradd g': 'ColorAdd_G',
  'coloradd gc': 'ColorAdd_GC',
  'coloradd gy': 'ColorAdd_GY',
  'coloradd m': 'ColorAdd_M',
  'coloradd r': 'ColorAdd_R',
  'coloradd ry': 'ColorAdd_RY',
  'coloradd uv': 'ColorAdd_UV',
  'coloradd w': 'ColorAdd_W',
  'coloradd ww': 'ColorAdd_WW',
  'coloradd y': 'ColorAdd_Y',
  'colorcalibrationmode': 'ColorCalibrationMode',
  'colorconsistency': 'ColorConsistency',
  'colorcontrol': 'ColorControl',
  'coloreffects': 'ColorEffects{n}',
  'colormacro': 'ColorMacro{n}',
  'colormacro 1 rate': 'ColorMacro{n}Rate',
  'colormacro 2 rate': 'ColorMacro{n}Rate',
  'colormixmode': 'ColorMixMode',
  'colormixmspeed': 'ColorMixMSpeed',
  'colormodelmode': 'ColorModelMode',
  'colorrgb blue': 'ColorRGB_Blue',
  'colorrgb cyan': 'ColorRGB_Cyan',
  'colorrgb green': 'ColorRGB_Green',
  'colorrgb magenta': 'ColorRGB_Magenta',
  'colorrgb quality': 'ColorRGB_Quality',
  'colorrgb red': 'ColorRGB_Red',
  'colorrgb yellow': 'ColorRGB_Yellow',
  'colorsub c': 'ColorSub_C',
  'colorsub m': 'ColorSub_M',
  'colorsub y': 'ColorSub_Y',
  'colorwheelselectmspeed': 'ColorWheelSelectMSpeed',
  'colour': 'Color{n}',
  'cols': 'Color{n}',
  'control': 'Control{n}',
  'cool': 'Color{n}',
  'crimode': 'CRIMode',
  'ctb': 'CTB',
  'ctc': 'CTC',
  'ctc rgbwl blend': 'CTC',
  'cto': 'CTO',
  'cw': 'ColorAdd_CW',
  'cw strobe dim': 'Shutter{n}Strobe',
  'cyan': 'ColorSub_C',
  'device settings': 'Function',
  'dim curve': 'Function',
  'dim curves': 'Function',
  'dim mode': 'Function',
  'dim modes': 'Function',
  'dim speed': 'Function',
  'dim strobe': 'Shutter{n}Strobe',
  'dimmer': 'Dimmer',
  'dimmer curve': 'Function',
  'dimmer curves': 'Function',
  'dimmer mode': 'Function',
  'dimmercurve': 'DimmerCurve',
  'dimmermode': 'DimmerMode',
  'dmxinput': 'DMXInput',
  'dummy': 'Dummy',
  'effect': 'Effects{n}',
  'effects': 'Effects{n}',
  'effects 1 fade': 'Effects{n}Fade',
  'effects 1 pos': 'Effects{n}Pos',
  'effects 1 posrotate': 'Effects{n}PosRotate',
  'effects 1 rate': 'Effects{n}Rate',
  'effects 2 adjust': 'Effects{n}Adjust1',
  'effects 2 fade': 'Effects{n}Fade',
  'effects 2 rate': 'Effects{n}Rate',
  'effects 3 fade': 'Effects{n}Fade',
  'effects 3 rate': 'Effects{n}Rate',
  'effectssync': 'EffectsSync',
  'empty': 'Control{n}',
  'fan': 'Fan{n}',
  'fan control': 'Control{n}',
  'fan mode': 'Function',
  'fanmode': 'FanMode',
  'fans': 'Fans',
  'fixed gobo': 'Gobo{n}',
  'fixtureglobalreset': 'FixtureGlobalReset',
  'focus': 'Focus{n}',
  'focus 1 adjust': 'Focus{n}Adjust',
  'focus 1 distance': 'Focus{n}Distance',
  'focusmode': 'FocusMode',
  'focusmspeed': 'FocusMSpeed',
  'frame': 'Blade{n}A',
  'frame 1 a': 'Blade{n}A',
  'frame 1 b': 'Blade{n}A',
  'frame 2 a': 'Blade{n}A',
  'frame 2 b': 'Blade{n}A',
  'frame 3 a': 'Blade{n}A',
  'frame 3 b': 'Blade{n}A',
  'frame 4 a': 'Blade{n}A',
  'frame 4 b': 'Blade{n}A',
  'frame rot': 'Blade{n}A',
  'framemspeed': 'FrameMSpeed',
  'free': 'Control{n}',
  'frost': 'Frost{n}',
  'function': 'Function',
  'functions': 'Function',
  'fx': 'Effects{n}',
  'fx param': 'Effects{n}',
  'fx select': 'Effects{n}',
  'fx speed': 'Effects{n}Rate',
  'fx wheel': 'Effects{n}',
  'g m point': 'Color{n}',
  'globalmspeed': 'GlobalMSpeed',
  'gobo': 'Gobo{n}',
  'gobo 1 pos': 'Gobo{n}Pos',
  'gobo 1 posrotate': 'Gobo{n}PosRotate',
  'gobo 1 rot': 'Gobo{n}',
  'gobo 1 selectspin': 'Gobo{n}SelectSpin',
  'gobo 1 wheelindex': 'Gobo{n}WheelIndex',
  'gobo 1 wheelmode': 'Gobo{n}WheelMode',
  'gobo 1 wheelspin': 'Gobo{n}WheelSpin',
  'gobo 2 pos': 'Gobo{n}Pos',
  'gobo 2 posrotate': 'Gobo{n}PosRotate',
  'gobo 2 rot': 'Gobo{n}',
  'gobo rot': 'Gobo{n}PosRotate',
  'gobo rotation': 'Gobo{n}PosRotate',
  'gobo shake': 'Gobo{n}SelectShake',
  'gobo wheel': 'Gobo{n}',
  'gobowheel 1 mspeed': 'GoboWheel{n}MSpeed',
  'gobrot': 'Gobo{n}PosRotate',
  'green': 'ColorAdd_G',
  'green magenta': 'ColorAdd_G',
  'haze': 'Haze{n}',
  'hsb brightness': 'HSB_Brightness',
  'hsb hue': 'HSB_Hue',
  'hsb saturation': 'HSB_Saturation',
  'int': 'Dimmer',
  'intensity': 'Dimmer',
  'intensitymspeed': 'IntensityMSpeed',
  'internal programs': 'Effects{n}',
  'iris': 'Iris',
  'lamp': 'LampControl',
  'lampcontrol': 'LampControl',
  'lamppowermode': 'LampPowerMode',
  'led dimmer': 'Dimmer',
  'ledfrequency': 'LEDFrequency',
  'ledzonemode': 'LEDZoneMode',
  'lens rotation': 'Control{n}',
  'lime': 'ColorAdd_GY',
  'macro color': 'Color{n}',
  'magenta': 'ColorSub_M',
  'master dimmer': 'Dimmer',
  'micropan': 'Pan',
  'microtilt': 'Tilt',
  'mode param': 'Function',
  'mode select': 'Function',
  'p t speed': 'PositionMSpeed',
  'pan': 'Pan',
  'pan infinite': 'Pan',
  'pan speed': 'PositionMSpeed',
  'pan tilt speed': 'PositionMSpeed',
  'panmode': 'PanMode',
  'panrotate': 'PanRotate',
  'pantiltmode': 'PanTiltMode',
  'pattern select': 'Effects{n}',
  'pattern selection': 'Effects{n}',
  'patterns': 'Effects{n}',
  'pixel blue': 'ColorAdd_B',
  'pixel green': 'ColorAdd_G',
  'pixel red': 'ColorAdd_R',
  'pixelmode': 'PixelMode',
  'plate blue': 'ColorAdd_B',
  'plate green': 'ColorAdd_G',
  'plate red': 'ColorAdd_R',
  'playmode': 'Playmode',
  'playspeed': 'PlaySpeed',
  'positioneffect': 'PositionEffect',
  'positioneffectrate': 'PositionEffectRate',
  'positionmodes': 'PositionModes',
  'positionmspeed': 'PositionMSpeed',
  'preset': 'FixtureGlobalReset',
  'prism': 'Prism{n}',
  'prism 1 macro': 'Prism{n}Macro',
  'prism 1 pos': 'Prism{n}Pos',
  'prism 1 posrotate': 'Prism{n}PosRotate',
  'prism 1 rot': 'Prism{n}',
  'prism 1 rotation': 'Prism{n}PosRotate',
  'prism 1 selectspin': 'Prism{n}SelectSpin',
  'prism 2 pos': 'Prism{n}Pos',
  'prism 2 posrotate': 'Prism{n}PosRotate',
  'prism 2 rot': 'Prism{n}',
  'prism 2 rotation': 'Prism{n}PosRotate',
  'prism rot': 'Prism{n}PosRotate',
  'prism rotation': 'Prism{n}PosRotate',
  'prog': 'Effects{n}',
  'prog speed': 'Effects{n}',
  'program': 'Effects{n}',
  'programs': 'Effects{n}',
  'pt speed': 'PositionMSpeed',
  'red': 'ColorAdd_R',
  'rgb dimmer': 'Dimmer',
  'ring blue': 'ColorAdd_B',
  'ring dimmer': 'Dimmer',
  'ring green': 'ColorAdd_G',
  'ring red': 'ColorAdd_R',
  'rot gobo': 'Gobo{n}',
  'rot y': 'Rot_Y',
  'rotating gobo wheel': 'Gobo{n}',
  'rotgobo': 'Gobo{n}PosRotate',
  'royal blue': 'ColorAdd_B',
  'saturation': 'HSB_Saturation',
  'shape blue': 'ColorAdd_B',
  'shape dimmer': 'Dimmer',
  'shape green': 'ColorAdd_G',
  'shape red': 'ColorAdd_R',
  'shape white': 'ColorAdd_W',
  'shapermacros': 'ShaperMacros',
  'shapermacrosspeed': 'ShaperMacrosSpeed',
  'shaperrot': 'ShaperRot',
  'shutter': 'Shutter{n}',
  'shutter 1 strobe': 'Shutter{n}Strobe',
  'shutter 1 strobeeffect': 'Shutter{n}StrobeEffect',
  'shutter 1 stroberandom': 'Shutter{n}StrobeRandom',
  'shutter strobe': 'Shutter{n}',
  'sound': 'Effects{n}',
  'special': 'Function',
  'special function': 'Function',
  'special functions': 'Function',
  'static gobo': 'Gobo{n}',
  'static gobo wheel': 'Gobo{n}',
  'strobe duration': 'Shutter{n}Strobe',
  'strobe freq': 'Shutter{n}Strobe',
  'strobe fx': 'Shutter{n}Strobe',
  'strobe mode': 'Shutter{n}Strobe',
  'strobe rate': 'Shutter{n}Strobe',
  'strobeduration': 'StrobeDuration',
  'strobefrequency': 'StrobeFrequency',
  'strobemode': 'StrobeMode',
  'strobemodeeffect': 'StrobeModeEffect',
  'strobemodeshutter': 'StrobeModeShutter',
  'strobemodestrobe': 'StrobeModeStrobe',
  'stroberate': 'StrobeRate',
  'tilt': 'Tilt',
  'tilt inf': 'Tilt',
  'tilt speed': 'PositionMSpeed',
  'tiltmode': 'TiltMode',
  'tiltrotate': 'TiltRotate',
  'tint': 'Tint',
  'top cw': 'ColorAdd_CW',
  'top ww': 'ColorAdd_WW',
  'total dimmer': 'Dimmer',
  'uv': 'ColorAdd_UV',
  'v col': 'Color{n}',
  'virtual color': 'Color{n}',
  'virtual color wheel': 'Color{n}',
  'warm white': 'ColorAdd_WW',
  'white': 'ColorAdd_W',
  'white amber': 'ColorAdd_RY',
  'ww': 'ColorAdd_WW',
  'x control': 'Control{n}',
  'xyz x': 'XYZ_X',
  'xyz y': 'XYZ_Y',
  'y control': 'Control{n}',
  'yellow': 'ColorSub_Y',
  'zoom': 'Zoom',
  'zoom rot': 'Zoom',
  'zoom rotation': 'Zoom',
  'zoommode': 'ZoomMode',
  'zoommspeed': 'ZoomMSpeed',
  'zoomreset': 'ZoomReset',
};
